### ISSUE TITLE
Publish to maven central or request to link the repository to jCenter repository

### ISSUE THREAD

**Issue by jsilva** [swoop-inc/spark-alchemy#10]
Would it be possible to publish the releases also to maven central repository or alternatively request to link the repository to jCenter repository ?

I would like to use this lib but unfortunately only maven central or Jcenter are mirrored to our internal Artifactory.

**Comment by greglu** [comment]
Thanks for the suggestion. I've requested the link to jcenter and it was approved: https://bintray.com/bintray/jcenter?filterByPkgName=spark-alchemy
