### ISSUE TITLE
README example on how to use NativeFunctionRegistration

### ISSUE THREAD

**Issue by MrPowers** [swoop-inc/spark-alchemy#2]
@ssimeonov - I read [your blog post](https://blog.simeonov.com/2018/11/14/apache-spark-native-functions/) and took a look at the [NativeFunctionRegistration trait](https://github.com/swoop-inc/spark-alchemy/blob/master/alchemy/src/main/scala/com/swoop/alchemy/spark/expressions/NativeFunctionRegistration.scala).

Can you provide a README example on how to use the `NativeFunctionRegistration` trait that's a little easier to follow for newbies than the `HyperLogLog` source code?  I'd like to understand the basics and then dive into the HyperLogLog code!

This library looks really cool.  Can't wait to understand all this code!

**Comment by ssimeonov** [comment]
@MrPowers yes, we have to add more docs. :)

As the comment in `NativeFunctionRegistration` says, this is code pulled from [`FunctionRegistry`](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala) in OSS Spark. 

Registering native functions is only necessary if you want to use them from SparkSQL. Using them from Scala simply requires creating a `Column`-oriented instantiation API as done in Spark's `functions`.

Once you have built one or more native functions, you create a registration object that extends `NativeFunctionRegistration` and implements `expressions`, e.g., the way [`HLLFunctionRegistration`](https://github.com/swoop-inc/spark-alchemy/blob/master/alchemy/src/main/scala/com/swoop/alchemy/spark/expressions/hll/HLLFunctionRegistration.scala) does.

To use the functions from SparkSQL, you have to register them by calling the equivalent of `HLLFunctionRegistration.register(spark)`.

That's all there is to it.
