### ISSUE TITLE
Spark 3.1 support

### ISSUE THREAD

**Issue by j03wang** [swoop-inc/spark-alchemy#21]
Any word on support for 3.1.x? Thanks!

**Comment by ssimeonov** [comment]
A 3.1.x PR would be welcome @j03wang.

**Comment by j03wang** [comment]
Seems like I can't even get it to compile, as one of the dependencies, `tut-plugin`, was only hosted on bintray, and I can't download the bits.

**Comment by pidge** [comment]
@greglu will cut a release

**Comment by greglu** [comment]
A new release has been deployed.

* Maven central - https://repo1.maven.org/maven2/com/swoop/spark-alchemy_2.12/1.1.0/
* GitHub Release - https://github.com/swoop-inc/spark-alchemy/releases/tag/v1.1.0
