### ISSUE TITLE
Python or Java support?

### ISSUE THREAD

**Issue by linbrian** [swoop-inc/spark-alchemy#4]
Hello, 

I was wondering if the HyperLogLog functions can be used in Java or Python (through Pyspark). I would assume so for Java. If there is support, I was wondering if examples can be posted on the Wiki. 

Thank you!

**Comment by cozos** [comment]
Hi, 

Based on these:

https://github.com/swoop-inc/spark-alchemy/wiki/Spark-Native-Functions
> To use the functions from SparkSQL, you have to register them by calling the equivalent of HLLFunctionRegistration.register(spark)

And https://github.com/swoop-inc/spark-alchemy/blob/master/alchemy/src/main/scala/com/swoop/alchemy/spark/expressions/NativeFunctionRegistration.scala#L20-L22

It seems like you can use all the functions here through SparkSQL:
https://github.com/swoop-inc/spark-alchemy/blob/master/alchemy/src/main/scala/com/swoop/alchemy/spark/expressions/hll/HLLFunctionRegistration.scala#L9-L16

**Comment by ssimeonov** [comment]
@cozos that's right and naive DSL support in other languages can be built by wrapping `functions.expr(<SparkSQL expression>)`.

@linbrian native DSL support for other languages requires a bit more work but there are lots of examples in Spark for how to do it. PRs welcome. :)

**Comment by ssimeonov** [comment]
Here is how to register the Spark native functions for HLL from Python: https://github.com/swoop-inc/spark-alchemy/issues/9#issuecomment-555155170

Java can use the Scala registration code directly.
